### ISSUE TITLE
Problem upgrading to Grails 2.3

### ISSUE THREAD

**Issue by maxifelix** [maxifelix/langSelector#1]
## Reported by Ludovik Lacroix

Hi Maximiliano,

I had a problem with locale selector plugin after the grails' upgrade to 2.3.
There was a session pb related to spring session's locale management in the Taglib:

Replaced :
def selected = session["org.springframework.web.servlet.i18n.SessionLocaleResolver.LOCALE"]

By:

Locale locale = RCU.getLocale(request)
def selected = locale.toString()

(just need to import org.springframework.web.servlet.support.RequestContextUtils as RCU).

BR
## 

Ludovik

**Comment by stokito** [comment]
Fixed
